version: "3.9"

services:
  device-service:
    container_name: device-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: device-service
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=2001
      - DB_NAME=devicestore
    networks:
      - app-net
    restart: unless-stopped

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: user-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=2001
      - DB_NAME=devicestore
    networks:
      - app-net
    restart: unless-stopped

  cart-service:
    container_name: cart-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: cart-service
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    environment:
    - DB_HOST=postgres
    - DB_USER=postgres
    - DB_PASSWORD=2001
    - DB_NAME=devicestore
    networks:
      - app-net
    restart: unless-stopped

  postgres:
    container_name: devicestore-postgres
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2001
      POSTGRES_DB: devicestore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:

volumes:
  postgres-data:
